const express = require('express');
const router = express.Router();

// Hardcoded test list for now (you can expand this)
const testList = [
  "ABO Blood Group and Rh Type",
  "ACTH (Adreno Corticotropic Hormone)",
  "AFB Rapid culture by MGIT - Tissue/Biopsy",
  "AFB-DNA (TB-PCR) Detection by RTPCR, Reﬂex to Rifampicin resistance by Ultra CBNAAT",
  "AFB-Xpert panel (M.Tb Detection & Rifamipicin resistance) by CBNAAT - Extra pulmonary samples",
  "AFB-Xpert panel (M.Tb Detection & Rifamipicin resistance) by CBNAAT - Pulmonary samples",
  "AFB-detection by smear examination ZN Stain Body ﬂuids",
  "AFB-detection by smear examination ZN Stain Sputum, 1 samples",
  "AFB-detection by smear examination ZN Stain Urine, 1 samples",
  "ANA Screening by IFA",
  "ANTI CCP (ACCP)",
  "APTT",
  "Abdomen mass biopsy -Medium 1-3 cm",
  "Accurate Reports",
  "Acetyl Choline Receptor Antibodies (AChRab)",
  "Acid Fast Bacilli Smear",
  "Acid Phosphatase",
  "Adenosine Deaminase (ADA)",
  "Adenosine Deaminase (ADA)(Ascitic ﬂuid)",
  "Adenosine Deaminase (ADA)(CSF)",
  "Adenosine Deaminase (ADA)(Pleural ﬂuid)",
  "Adenosine Deaminase (ADA)(Pus)",
  "Alanine Transaminase (SGPT)",
  "Albumin",
  "Albumin creatinine ratio (ACR) - Spot sample",
  "Alcohol Ethanol Serum",
  "Aldosterone",
  "Alkaline Phosphatase",
  "Allergen, Individual-Micro organism Aspergillus Fumigatus fungus",
  "Alpha Feto Protein (AFP)",
  "Amylase",
  "Androstenedione (A4)",
  "Angiotensin Converting Enzyme (ACE)",
  "Anti Chlamydia Antibody Igm",
  "Anti Ds-DNA",
  "Anti HCV IgM",
  "Anti Hepatitis A Virus (ANTI HAV) - IgG",
  "Anti Hepatitis A Virus (ANTI HAV) - IgM",
  "Anti Hepatitis B Core Antibody (AHBC) - IGM",
  "Anti Hepatitis B Core Antibody (AHBc) - Total",
  "Anti Hepatitis B Envelope Antibody (AHBe) -Total",
  "Anti Hepatitis C Virus (HCV) - Total",
  "Anti Hepatitis E Virus (HEV) - IgG",
  "Anti Hepatitis E Virus (HEV) - IgM",
  "Anti Mitochondrial Antibody",
  "Anti Mullerian Hormone (AMH)",
  "Anti Nuclear Antibodies (ANA)",
  "Anti Phospholipid Antibody (APL) - IgG",
  "Anti Phospholipid Antibody (APL) - IgM",
  "Anti TPO",
  "Anti-Hepatitis B Surface antibodies (Anti-HBs titre)",
  "Anti-Smooth Muscle Antibody",
  "Anti-Streptolysin O (ASO)",
  "Anti-microsomal antibodies",
  "Anti-ro SSA Antibodies by EIA",
  "Apo B: Apo A1 ratio",
  "Apolipoprotein - A1",
  "Apolipoprotein - B",
  "Appendix -Large Biopsy 3-6 cm",
  "Arthritis Basic Screening",
  "Aspartate AminoTransferase (SGOT )",
  "Aspergillosis IgG antibodies",
  "Aspergillosis IgM antibodies",
  "BUN/Creatinine ratio",
  "Basic Health Checkup",
  "Beta 2 Glycoprotein 1 - IgG",
  "Beta 2 Glycoprotein 1 - IgM",
  "Beta 2 Microglobulin",
  "Beta HCG",
  "Beta-Thalassemia Screenig with Graph",
  "Bicarbonate",
  "Bile Acids",
  "Bilirubin Direct",
  "Bilirubin Total",
  "Biotinidase Enzyme Activity",
  "Blood C/S - BacT/Alert (with bottle)",
  "Blood C/S - BacT/Alert (without bottle)",
  "Blood Toxic Element Proﬁle",
  "Blood Urea Nitrogen (BUN)",
  "Body Fluid Analysis (Other) - Body Fluid",
  "Body Fluid Analysis - Plerual Fluid",
  "Body Fluid Analysis -Ascitic Fluid",
  "Body ﬂuid analysis for malignant cells",
  "Breast biopsy -Medium 1-3 cm",
  "Breast biopsy -small <1cm",
  "Breast lump",
  "Brucella IgM",
  "C - Reactive Protein (CRP)",
  "C-Peptide Fasting",
  "C-Peptide PP",
  "CA 19.9",
  "CA125",
  "CA15.3",
  "CAP*",
  "CBC-Complete Blood Count",
  "CBC-Complete Hemogram Test(28)",
  "CD3/CD4/CD8",
  "CDC*",
  "Calcitonin",
  "Calcium",
  "Calcium creatinine ratio (Spot)",
  "Calprotectin",
  "Carcino Embryonic Antigen (CEA)",
  "Cardiolipin Antibody (ACL) -IgA",
  "Cardiolipin Antibody (ACL) -IgG",
  "Cardiolipin Antibody (ACL) -IgM",
  "Ceruloplasmin",
  "Cervix biopsy -Medium 1-3 cm",
  "Cervix biopsy -small <1cm",
  "Cheek biopsy -small <1cm",
  "Chikungunya Combo Rapid Test",
  "Chikungunya IgG Rapid antibody",
  "Chikungunya IgM Rapid antibody",
  "Chloride",
  "Colon biopsy -small <1cm",
  "Complement 3 (C3)",
  "Complement 4 (C4)",
  "Comprehensive Full Body Checkup with Vitamin D",
  "Cortisol (4:00 PM)",
  "Cortisol (8:00 AM)",
  "Covid 19 Antibodies - Total",
  "Covid Well",
  "Creatine Kinase-MB (CK-MB)",
  "Creatinine Phospho Kinase (CPK) - Total",
  "Culture & Sensitivity, Aerobic bacteria Blood 1 Aerobic,1-Anerobic",
  "Culture & Sensitivity, Aerobic bacteria Blood single bottle",
  "Culture & Sensitivity, Aerobic bacteria Body Fluids Specify type",
  "Culture & Sensitivity, Aerobic bacteria CSF",
  "Culture & Sensitivity, Aerobic bacteria Other samples",
  "Culture & Sensitivity, Aerobic bacteria Pus",
  "Culture & Sensitivity, Aerobic bacteria Semen",
  "Culture & Sensitivity, Aerobic bacteria Sputum",
  "Culture & Sensitivity, Aerobic bacteria Stool",
  "Culture & Sensitivity, Aerobic bacteria Throat Swab",
  "Culture & Sensitivity, Aerobic bacteria Urine",
  "Cystatin - C",
  "Cytomegalo Virus (CMV) - IgG",
  "Cytomegalo Virus (CMV) - IgM",
  "D-DIMER",
  "DCP-Decarboxy Prothrombin PIVKA-II",
  "DELHI (E) | DELHI (W) | DELHI (C) | LUCKNOW | RANCHI | BHUBANESWAR | PATNA",
  "DHEA-Sulphate (DHEAS)",
  "Dengue -IgG (CLIA)",
  "Dengue -IgG (ELISA)",
  "Dengue -IgM (CLIA)",
  "Dengue -IgM (ELISA)",
  "Dengue IgG (Rapid)",
  "Dengue IgM (Rapid)",
  "Dengue NS-1 Antigen (CLIA)",
  "Dengue NS-1 Antigen (ELISA)",
  "Dengue NS-1 Antigen (Rapid)",
  "Desmoglein I Antibody",
  "Desmoglein III Antibody",
  "Di Hydro Testosterone (DHT)",
  "Direct Coombs Test",
  "Double Marker - First Trimester",
  "ERNDIM*",
  "ESR (Erythrocyte Sedimentation Rate)",
  "Endometrium biopsy -Medium 1-3 c",
  "Eosinophils-Absolute Count",
  "Erythropoietin",
  "Estradiol",
  "FNAC",
  "FSH, LH & Prolactin",
  "Factor VIII Activity",
  "Ferritin",
  "Fever Plus Proﬁle",
  "Fever Proﬁle",
  "Fibrinogen",
  "Fistula -Medium 1-3 Biopsy cm",
  "Folic acid",
  "Follicle Stimulating Hormone (FSH)",
  "For us at GD, our calling is to care for the sick and aid the doctors to",
  "For us at GD-",
  "Free Beta HCG",
  "Free PSA",
  "Free PSA/Total PSA ratio",
  "Free TFT (Free T3,Free T4,TSH)",
  "Free Testosterone",
  "Free Thyroxine (FT4)",
  "Free Triiodothyronine (FT3)",
  "Freedom A- 2022",
  "Freedom B- 2022",
  "Fructosamine",
  "Fungal Culture",
  "Fungal Stain (KOH Mount)",
  "GAD 65 Antibody by IFA (for Paraneoplastic syndrome)",
  "GAD Total Antibody",
  "GB specimen -Medium Biopsy 1-3 cm",
  "Gall bladder -Large Biopsy 3-6 cm",
  "Gamma Glutamyl Transferase (GGT)",
  "Genxpert",
  "Globulin",
  "Glucose Challenge Test (2hours after 75gm Glucose load)",
  "Glucose-6-Phosphate Dehydrogenase (G6PD) Whole Blood",
  "Gram Stain",
  "H1N1 (Swine Flu) RNA Detection by Real Time PCR - Swab",
  "HBV DNA Quantitative Viral Load",
  "HCV Card test",
  "HCV – RNA PCR (Qualitative)",
  "HCV – RNA PCR (Quantitative)",
  "HCV-Genotyping by sequencing",
  "HDL Cholesterol",
  "HELICOBACTER PYLORI - IgA (ELISA)",
  "HELICOBACTER PYLORI - IgG (CLIA)",
  "HELICOBACTER PYLORI - IgM (ELISA)",
  "HIV (Rapid Card Test)",
  "HIV - I & II",
  "HIV - Western Blot",
  "HIV RNA Detection by RT_PCR (Qualitative)",
  "HIV p24 Antigen",
  "HLA B27 studies (PCR)",
  "HLAB27",
  "Haptoglobin Serum",
  "Hba1c (Whole Blood)",
  "Hba1c (Whole Blood) with Graph",
  "HbsAg (Rapid Card test)",
  "Helicobacter Pylori Antigen detection by  - Stool",
  "Hemoglobin",
  "Hemoglobinopathy Proﬁle - HbF/HbS",
  "Hemoglobinopathy Proﬁle - HbF/HbS (with Graph)",
  "Hepatitis B Envelope Antigen (HBeAg)",
  "Hepatitis B Surface Antigen (HBsAg) (Quantitative)",
  "Herpes Simplex Virus (HSV I & II)-IgG",
  "Herpes Simplex Virus I (HSV)-IgG",
  "Herpes Simplex Virus I (HSV)-IgM",
  "Herpes Simplex Virus II (HSV)-IgG",
  "Herpes Simplex Virus II (HSV)-IgM",
  "High Sensitivity C-Reactive Protein (hs- CRP)",
  "Homocysteine",
  "Human Growth Harmone (HGH)",
  "Immature Platelets Fraction (IPF)",
  "Immunoglobulin  M (IgM)",
  "Immunoglobulin A (IgA)",
  "Immunoglobulin G (IgG)",
  "Immunoﬁxation (Quantitative)",
  "India’s lifelong, most reliable diagnostics partner.",
  "Indirect Coombs Test",
  "Inhibin -A",
  "Insulin Fasting",
  "Insulin PP",
  "Insulin – like Growth Factor (IGF -1)",
  "Interleukin 6 IL6",
  "Inﬂuenza Panel by RT-PCR",
  "Ionised Calcium",
  "Iron",
  "Iron Studies (Iron,TIBC, Transferrin saturation)",
  "KOLKATA | NASHIK | PUNE | MUMBAI (W1) | MUMBAI (W2) | MUMBAI (C) | NAVI MUMBAI",
  "Karyotyping - Blood",
  "Karyotyping - Blood (Husband)",
  "Karyotyping - Blood (Wife)",
  "Ketone by Fully Automated Urine chemistry & Microscopy",
  "Kidney Proﬁle",
  "LDL Cholesterol - Direct",
  "LE cell test",
  "LFT (Liver Function Test)",
  "LH/FSH Ratio",
  "LKM1 Antibodies (Liver Kidney Microsomes)",
  "Lactate",
  "Lactate Dehydrogenase (LDH Serum)",
  "Lead (Blood)",
  "Leptospira IgG",
  "Leptospira IgG & IgM Rapid",
  "Leptospira IgM",
  "Leptospira IgM Rapid",
  "Lipase",
  "Lipid Proﬁle",
  "Lipoprotein (A) [Lp(a)]",
  "Lithium",
  "Lupus Anticoagulants",
  "Luteinizing Hormone (LH)",
  "Lymph node biopsy -Medium 1-3 cm",
  "MPO - ANCA ( P - ANCA )",
  "Magnesium",
  "Malarial Antigen Detection",
  "Mass -Medium Biopsy 1-3 cm",
  "Master Full Body Checkup (Female)",
  "Master Full Body Checkup (Male)",
  "Max Kidney Proﬁle",
  "Microalbumin",
  "Microalbumin 24 hours",
  "Microalbumin Creatinine Ratio - Spot Sample",
  "Microalbumin creatinine ratio- 24 Hours Urine",
  "Microalbumin creatinine ratio- Spot Urine",
  "Microﬁlaria Antibody",
  "Monsoon Essential Panel",
  "Monsoon Wellness Package - 2022",
  "Mumps Virus IgG antibody",
  "Mycoplasma Pneumoniae IgM",
  "NABL",
  "NT-Pro BNP",
  "Neonatal Hemoglobinopathy Proﬁle",
  "Noninvasive prenatal Screening (NIPS/NIPT)",
  "Ovarian cyst -Large Biopsy 3-6 cm",
  "PACKAGE NAME",
  "PAP Smear - Conventional",
  "PAP Smear - Liquid Based Cytology",
  "PAPPA (Pregnancy Associated Plasma Protein -A)",
  "PBS for Schistocytes",
  "PR3 - ANCA ( C-ANCA )",
  "PTH -Intact (Parathyroid Hormone)",
  "Pancreatic Proﬁle (2 Parameters)",
  "Patient welfare",
  "Peripheral blood smear (PBS)",
  "Phadiatop",
  "Phenytoin",
  "Pheripheral Blood Smear",
  "Phosphorus",
  "Platelet Count",
  "Potassium",
  "Procalcitonin",
  "Progesterone",
  "Prolactin",
  "Prostate Speciﬁc Antigen (PSA)-Total",
  "Protein C Activity",
  "Protein Creatinine Ratio (PCR) - Spot Sample",
  "Protein Electrophoresis",
  "Protein S Activity",
  "Protein creatinine ratio (Spot)",
  "Prothrombin Time (PT with INR)",
  "Pus Routine Microscopy",
  "Quadruple Marker - Second Trimester",
  "QuantiFERON-TB Gold (Interferon-gamma release assay (IGRA)",
  "Rectal biopsy -small <1cm",
  "Reducing Substances- Stool",
  "Republic A",
  "Republic B",
  "Reticulocyte Count",
  "Rh Antibody Titre",
  "Rheumatoid Factor (RF)",
  "Rubella  - IgG",
  "Rubella  - IgM",
  "SARS-COV-2 Spike protein IgG Antibodies",
  "SARS-CoV-2 RT-PCR",
  "SERUM  ZINC (By Photometry)",
  "SERUM COPPER (By Photometry)",
  "Scrub typhus IgM by EIA - Serum",
  "Serum Bilirubin - Total & Direct",
  "Serum Creatinine",
  "Serum Electrolyte Proﬁle",
  "Serum Insulin PP after 75gm Glucose load",
  "Sex Hormone Binding Globulin (SHBG)",
  "Sickling Test",
  "Smear for MF (Microﬁlaria)",
  "Smear for MP (Malarial Parasite)",
  "Sodium",
  "Spot Urinary Creatinine",
  "Spot Urinary protein",
  "Sputum Routine",
  "Stone Analysis Kidney (Renal) calculus",
  "Stool Routine",
  "Stool for Occult Blood",
  "Sugar (Glucose) Fasting",
  "Sugar (Glucose) Post Prandial",
  "Sugar (Glucose) Random",
  "Syphilis TP",
  "TOXOPLASMA  GONDII - IgM",
  "TOXOPLASMA GONDII - IgG",
  "TSH (Thyroid Stimulating Hormone)",
  "TSH - Receptor Antibody (IgG)",
  "TSH Ultra Sensitive",
  "Testosterone",
  "Thyroglobulin - Cancer Marker",
  "Thyroid Auto Antibodies (Anti-TG & Anti-TPO)",
  "Thyroid Proﬁle  - Total T3,Total T4,TSH (TFT)",
  "Thyroid Proﬁle (5 Parameters)",
  "Timely Delivered.",
  "Tissue Transglutaminase - Iga (TTG)",
  "Tissue Transglutaminase IgG (TTG)",
  "Top 400 Tests - P1 OLD",
  "Total Cholesterol",
  "Total IGE",
  "Total Iron Binding Capacity (TIBC)",
  "Total Leucocytes Count",
  "Total Protein",
  "Total Protein, Albumin, Globulin,A/G ratio",
  "Total Thyroxine (T4)",
  "Total Triiodothyronine (T3)",
  "Toxoplasma Gondii - IgM",
  "Treponema Pallidum Haemagglutination(TPHA)",
  "Triglycerides",
  "Triple Marker-Second Trimester",
  "Troponine T",
  "Typhi Dot IgG",
  "Typhi Dot IgG & IgM",
  "Typhi Dot IgM",
  "Urea",
  "Uric Acid",
  "Urinary Copper 24 hours",
  "Urinary Electrolytes Spot",
  "Urinary Sodium (Spot)",
  "Urinary Urea Spot",
  "Urine Bence Jones Proteins- BJP",
  "Urine C/S",
  "Urine Complete",
  "Urine Osmolality",
  "Urine Pregnancy test",
  "Urine Sugar (Fasting)",
  "Urine Sugar (PP)",
  "Urine Sugar Random",
  "Urine by Liquid based cytology",
  "Uterus +Cervix+ 2 Falopian tube+2 Overy Biopsy -XL",
  "Uterus Biopsy -XL",
  "Uterus Cervix -Large Biopsy 3-6 cm",
  "Uterus Cervix Biopsy-XL",
  "Uterus mass -Large Biopsy 3-6 cm",
  "VDRL (RPR)",
  "Valproic acid",
  "Varicella Zooster IgG",
  "Varicella Zooster IgM",
  "Vitamin B12",
  "Vitamin B12 - Active",
  "Vitamin B6",
  "Vitamin D1,25 Dihydroxy",
  "Vitamin D3",
  "Weil Felix",
  "Widal Slide Test (4Hrs)",
  "ZINC (Blood)",
  "eGFR (estimated Glomerular Filtration Rate)",
  
];

// GET route to send the test list
router.get('/', (req, res) => {
  res.json(testList);
});

module.exports = router;
